# Feature Extraction

In [1]:
import nltk
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
text = "hello i am kushal. i live in gongabu. what is your name?"

In [3]:
tokens = nltk.word_tokenize(text)

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
cvect = CountVectorizer().fit(tokens)

In [6]:
cvect

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [7]:
cvect.get_feature_names()

['am',
 'gongabu',
 'hello',
 'in',
 'is',
 'kushal',
 'live',
 'name',
 'what',
 'your']

In [8]:
test = "programmming is loved by kushal"

In [9]:
test_vect = cvect.transform(nltk.word_tokenize(test))

In [10]:
test_vect.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0]])

In [11]:
pd.DataFrame(test_vect.toarray(),columns=cvect.get_feature_names())

am  gongabu  hello  in  is  kushal  live  name  what  your
0   0        0      0   0   0       0     0     0     0     0
1   0        0      0   0   1       0     0     0     0     0
2   0        0      0   0   0       0     0     0     0     0
3   0        0      0   0   0       0     0     0     0     0
4   0        0      0   0   0       1     0     0     0     0

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [13]:
tfidf_vect = TfidfVectorizer().fit(tokens)
tfidf_vect

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [14]:
test_vect = tfidf_vect.transform(nltk.word_tokenize(text))

In [15]:
test_vect

<15x10 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [16]:
test_vect.toarray()

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# Part 2

In [17]:
train = ["Hello i am kushal",
        "I love programmming",
        "My exams are comming soon",
         "Today i am doing NLP"]

In [18]:
test = [" today i am free and i am programming "]

In [19]:
count_vectorizer = CountVectorizer().fit(train)
print(count_vectorizer.get_feature_names())

['am', 'are', 'comming', 'doing', 'exams', 'hello', 'kushal', 'love', 'my', 'nlp', 'programmming', 'soon', 'today']


In [20]:
vect = count_vectorizer.transform(test)
print(vect.toarray())

[[2 0 0 0 0 0 0 0 0 0 0 0 1]]


In [21]:
pd.DataFrame(vect.toarray(), columns=count_vectorizer.get_feature_names() )

am  are  comming  doing  exams  hello  kushal  love  my  nlp  programmming  \
0   2    0        0      0      0      0       0     0   0    0             0   

   soon  today  
0     0      1

In [22]:
tfidf_vectorizer = TfidfVectorizer().fit(train)
print(tfidf_vectorizer.get_feature_names())

['am', 'are', 'comming', 'doing', 'exams', 'hello', 'kushal', 'love', 'my', 'nlp', 'programmming', 'soon', 'today']


In [23]:
vect = tfidf_vectorizer.transform(test)
print(vect.toarray())

[[0.8444932  0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.53556627]]


In [24]:
pd.DataFrame(vect.toarray(), columns=tfidf_vectorizer.get_feature_names() )


am  are  comming  doing  exams  hello  kushal  love   my  nlp  \
0  0.844493  0.0      0.0    0.0    0.0    0.0     0.0   0.0  0.0  0.0   

   programmming  soon     today  
0           0.0   0.0  0.535566